'use strict';
const $ = (s, root = document) => root.querySelector(s);
const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cash = cents => '¥' + (cents / 100).toLocaleString('zh-CN', {minimumFractionDigits:2, maximumFractionDigits:2});
const isoLocal = () => { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; };
const add = (d, n) => { const x = new Date(d + 'T12:00:00'); x.setDate(x.getDate() + n); return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`; };
const nights = (a,b) => Math.round((new Date(b+'T12:00:00') - new Date(a+'T12:00:00')) / 86400000);
const short = d => d.slice(5).replace('-','/');
const weekday = d => '周' + '日一二三四五六'[new Date(d+'T12:00:00').getDay()];
let state, view='rooms', selected=isoLocal(), roomMode='cards', syncDate=isoLocal(), syncDays=14, pendingOnly=true, orderQuery='', orderFilter='未完成', busy=false;
let modalRevision=0, toastTimer;
const modal = $('#modal');
const typeOf = room => Object.keys(state.rooms).find(k=>state.rooms[k].includes(room));
const allRooms = () => Object.values(state.rooms).flat();
const endOf = b => b.status==='在住' && b.end<=state.today ? add(state.today,1) : b.end;
const occupies = (b,d) => b.status!=='已取消' && b.start<=d && d<endOf(b);
const atRoom = (r,d) => state.bookings.find(b=>b.room===r && occupies(b,d));
const paid = b => state.payments.filter(p=>p.bookingId===b.id).reduce((a,p)=>a+p.amount,0);
const statusClass = s => ({'在住':'occupied','预订':'reserved','停用':'blocked','已退房':'blocked','已取消':'blocked'}[s]||'');
const badge = s => `<span class="badge ${statusClass(s)}">${esc(s)}</span>`;
function alloc(d,k){
  const free=state.rooms[k].filter(r=>!atRoom(r,d)).length, custom=state.overrides[d+'|'+k];
  let offline,ctrip,meituan;
  if(custom){offline=Math.min(free,custom.offline);ctrip=Math.min(custom.ctrip,free-offline);meituan=Math.min(custom.meituan,free-offline-ctrip);offline=free-ctrip-meituan;}
  else{offline=Math.min(state.settings.reserve[k],free);const online=free-offline;ctrip=Math.ceil(online/2);meituan=Math.floor(online/2);}
  const confirmed=state.confirmed[d+'|'+k];
  return {free,offline,ctrip,meituan,confirmed,pending:!confirmed||confirmed.ctrip!==ctrip||confirmed.meituan!==meituan};
}
function pendingCount(){let n=0;for(let i=0;i<14;i++)for(const k in state.rooms)if(alloc(add(state.today,i),k).pending)n++;return n;}
function toast(text){$('#toast').textContent=text;$('#toast').classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.add('hidden'),4200);}
async function refresh(initial=false){
  try{const res=await fetch('/api/state');if(!res.ok)throw Error();const next=await res.json();const changed=!state||state.revision!==next.revision||state.today!==next.today;state=next;$('#offline').classList.add('hidden');$('#connectionDot').classList.add('online');$('#connectionText').textContent='本机数据已保存';if(changed&&!modal.open)render();}
  catch(e){$('#offline').classList.remove('hidden');$('#connectionDot').classList.remove('online');$('#connectionText').textContent='未连接';if(initial)$('#content').innerHTML='<div class="empty"><strong>暂时连接不到本机服务</strong>请运行 start-frontdesk.cmd，再刷新本页。</div>';}
}
async function save(action,payload,revision=modalRevision){
  if(['allocate','confirm'].includes(action)&&modal.dataset.through)payload={...payload,through:modal.dataset.through};
  if(busy)return false;busy=true;const buttons=[...modal.querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);$('#formError')?.remove();
  try{const response=await fetch('/api/'+action,{method:'POST',headers:{'Content-Type':'application/json','X-Kasho-Request':'frontdesk'},body:JSON.stringify({...payload,revision})});const next=await response.json();if(!response.ok)throw Error(next.error||'保存失败');state=next;modal.close();render();toast('已保存到本机'+(['booking','settings','allocate'].includes(action)?'，请查看平台调房提醒':''));return true;}
  catch(e){const target=$('.modal-body');if(target){const err=document.createElement('div');err.id='formError';err.className='error';err.textContent=e.message;target.append(err);err.scrollIntoView({block:'nearest'});}else toast(e.message);return false;}
  finally{busy=false;buttons.forEach(b=>b.disabled=false);}
}
function render(){
  if(!state)return;const titles={rooms:'房态总览',sync:'平台调房',orders:'订单与收款',settings:'设置与备份'};
  $('#pageTitle').textContent=titles[view];$('#clockLabel').textContent=state.today+' '+weekday(state.today);const n=pendingCount();$('#navPending').textContent=n;$('#navPending').classList.toggle('hidden',!n);
  document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));
  const overdue=state.bookings.filter(b=>b.status==='在住'&&b.end<=state.today);
  $('#overdue').innerHTML=overdue.length?`<div class="notice danger"><div><strong>${overdue.length} 间到期在住，尚未确认退房</strong>${overdue.map(b=>esc(b.room)).join('、')}：今日暂不作为空房，请尽快登记续住或退房。</div><button data-action="edit" data-id="${overdue[0].id}">处理房间</button></div>`:'';
  $('#content').innerHTML=({rooms:renderRooms,sync:renderSync,orders:renderOrders,settings:renderSettings})[view]();
}
function stats(items){return '<div class="stats">'+items.map(([label,val,hint])=>`<div class="stat"><label>${label}</label><strong>${val}</strong><p>${hint}</p></div>`).join('')+'</div>';}
function renderRooms(){
  const occupied=allRooms().filter(r=>atRoom(r,selected)).length, arrivals=state.bookings.filter(b=>b.start===selected&&['预订','在住'].includes(b.status)).length, departures=state.bookings.filter(b=>b.end===selected&&['预订','在住'].includes(b.status)).length;
  const receipts=state.payments.filter(p=>p.at.slice(0,10)===selected).reduce((n,p)=>n+p.amount,0), pending=pendingCount();
  let html=state.bookings.length===0?'<div class="notice info"><div><strong>首次使用：先录入现有入住和未来预订</strong>当前是空账本，“13 间可安排”不是实际库存。请先录齐携程、美团和线下订单，再按建议调房。</div><button data-view="settings">设置参考房价</button></div>':'';
  html+=pending?`<div class="notice"><div><strong>两平台房量待核对</strong>未来 14 天有 ${pending} 条“日期 × 房型”尚未核对或已变化。相同房量的连续日期已合并，方便一次核对多晚。</div><button data-view="sync">去处理 ⇢</button></div>`:'';
  html+=stats([['可安排房间',`${13-occupied}<small> / 13 间</small>`,'所选日夜间剩余 · 已扣预订及停用'],['待抵店',`${arrivals}<small> 笔</small>`,'所选日抵店订单 · 含已入住'],['计划离店',`${departures}<small> 笔</small>`,'所选日离店 · 需前台确认'],['登记净收款',cash(receipts),'所选日登记收款 − 退款']]);
  html+=`<div class="toolbar"><button data-action="dayPrev" aria-label="前一天">‹</button><input id="roomDate" type="date" aria-label="查看日期" value="${selected}"><button data-action="dayNext" aria-label="后一天">›</button><button data-action="today">今天</button><div class="spacer"></div><div class="segmented"><button data-mode="cards" class="${roomMode==='cards'?'selected':''}">房间卡片</button><button data-mode="timeline" class="${roomMode==='timeline'?'selected':''}">7 天房态</button></div><div class="legend"><span>空房</span><span class="occupied">在住</span><span class="reserved">预订</span><span class="blocked">停用 / 已退</span></div></div>`;
  if(roomMode==='timeline')return html+renderTimeline();
  for(const[k,rooms]of Object.entries(state.rooms)){
    const free=rooms.filter(r=>!atRoom(r,selected)).length;
    html+=`<div class="room-group"><div class="group-heading"><h3>${esc(k)}</h3><span>${rooms.length} 间 · 可安排 ${free} 间</span></div><div class="room-grid">`;
    for(const r of rooms){const b=atRoom(r,selected);html+=`<button class="room-card ${b?'is-'+statusClass(b.status):'is-free'}" data-action="${b?'edit':'new'}" data-room="${r}" ${b?'data-id="'+b.id+'"':''}><span class="room-top"><strong class="room-number">${r}</strong>${badge(b?b.status:'空房')}</span><span class="guest">${b?esc(b.guest):'可以安排入住'}</span><span class="room-detail"><span>${b?esc(b.channel)+' · '+short(b.end)+' 离店':'点击登记入住 / 预订'}</span><span>${b?(b.status==='停用'?'':cash(b.total-paid(b))+' 待收'):'＋'}</span></span></button>`;}
    html+='</div></div>';
  }return html;
}
function renderTimeline(){
  const days=Array.from({length:7},(_,i)=>add(selected,i));
  return `<div class="panel"><div class="table-wrap"><table class="timeline"><thead><tr><th>房号 / 房型</th>${days.map(d=>`<th>${short(d)} ${weekday(d)}${d===state.today?' · 今天':''}</th>`).join('')}</tr></thead><tbody>${allRooms().map(r=>`<tr><td><strong>${r}</strong><small>${esc(typeOf(r))}</small></td>${days.map(d=>{const b=atRoom(r,d);return `<td><button class="${b?statusClass(b.status):''}" data-action="${b?'edit':'new'}" data-room="${r}" data-date="${d}" ${b?'data-id="'+b.id+'"':''}><span class="cell-name">${b?esc(b.guest):'空房 ＋'}</span><span class="cell-sub">${b?esc(b.channel)+' · '+esc(b.status):'可安排'}</span></button></td>`;}).join('')}</tr>`).join('')}</tbody></table></div></div>`;
}
function renderSync(){
  let rows='',count=0;
  const groups=[];
  for(const k in state.rooms){let group=null;for(let i=0;i<syncDays;i++){const d=add(syncDate,i),a=alloc(d,k);if(pendingOnly&&!a.pending){group=null;continue;}count++;const signature=JSON.stringify([a.free,a.ctrip,a.meituan,a.offline,a.pending,a.confirmed?.ctrip,a.confirmed?.meituan]);if(group&&group.signature===signature){group.end=d;}else{group={d,end:d,k,a,signature};groups.push(group);}}}
  groups.sort((a,b)=>a.d.localeCompare(b.d)||Object.keys(state.rooms).indexOf(a.k)-Object.keys(state.rooms).indexOf(b.k));
  for(const{d,end,k,a}of groups){rows+=`<tr class="${a.pending?'pending-row':''}"><td><strong>${d}${end!==d?' → '+end:''}</strong><small>${end!==d?'共 '+(nights(d,end)+1)+' 晚 · 每晚相同':weekday(d)}</small></td><td>${esc(k)}</td><td class="number">${a.free}</td><td><strong class="number">${a.ctrip}</strong><small>${a.ctrip===0?'应关房':'每晚可售'}</small></td><td><strong class="number">${a.meituan}</strong><small>${a.meituan===0?'应关房':'每晚可售'}</small></td><td>${a.offline}</td><td>${a.confirmed?`上次 ${a.confirmed.ctrip} / ${a.confirmed.meituan}<small>${a.pending?'需要重新核对':'已记录人工核对'}</small>`:'<span class="pending-text">尚未核对</span>'}</td><td><div class="actions"><button class="small" data-action="allocate" data-date="${d}" data-through="${end}" data-kind="${esc(k)}">分配</button><button class="small ${a.pending?'primary':''}" data-action="confirm" data-date="${d}" data-through="${end}" data-kind="${esc(k)}">${a.pending?'核对并确认':'重新核对'}</button></div></td></tr>`;}
  return `<div class="notice"><div><strong>这是人工调房清单，系统尚未连接携程 / 美团</strong>建议数是“剩余可售间数”，不是总房间数。先在两平台减少 / 关房，再增加；核对同一天、同房型全部可售产品后再确认。两平台未更新期间仍可能超售。</div></div><div class="toolbar"><label class="date-caption" for="syncDate">起始日期</label><input id="syncDate" type="date" min="${state.today}" value="${syncDate}"><select id="syncDays" aria-label="查看天数"><option value="14" ${syncDays===14?'selected':''}>未来 14 天</option><option value="30" ${syncDays===30?'selected':''}>未来 30 天</option><option value="90" ${syncDays===90?'selected':''}>未来 90 天</option></select><button data-action="togglePending">${pendingOnly?'当前：只看待处理':'当前：查看全部'}</button><span class="spacer"></span><span class="sync-window">默认均分线上房量；奇数多分 1 间给携程</span></div><div class="panel"><div class="panel-head"><div><h2>按日期调整平台库存</h2><p>携程 + 美团 + 线下留房 = 当天可安排间数 · 共 ${count} 条</p></div></div>${rows?`<div class="table-wrap"><table><thead><tr><th>入住日期</th><th>房型</th><th>剩余</th><th>携程 →</th><th>美团 →</th><th>线下</th><th>上次人工核对</th><th>操作</th></tr></thead><tbody>${rows}</tbody></table></div>`:'<div class="empty"><strong>这个日期范围已核对完成</strong>新订单或续住改变建议房量后，会再次提醒。平台实际库存仍需前台留意。</div>'}</div><p class="muted">首页提醒覆盖未来 14 天；较远的预订 / 续住，请切换日期范围核对。平台退款、取消、续住也要同步登记到本系统。</p>`;
}
function renderOrders(){
  const active=state.bookings.filter(b=>!['已取消','停用'].includes(b.status)),due=active.reduce((n,b)=>n+b.total-paid(b),0),net=state.payments.reduce((n,p)=>n+p.amount,0);
  let orders=state.bookings.filter(b=>(orderFilter==='全部'||(orderFilter==='未完成'?['预订','在住','停用'].includes(b.status):b.status===orderFilter))&&`${b.room} ${b.guest} ${b.phone} ${b.reference} ${b.channel}`.toLowerCase().includes(orderQuery.toLowerCase())).sort((a,b)=>b.start.localeCompare(a.start)||b.id-a.id);
  return stats([['待收房费',cash(due),'全部有效订单 · 订单总额 − 已收'],['累计净收款',cash(net),'全部登记收款 − 退款 · 非平台自动账单'],['有效订单',`${active.length}<small> 笔</small>`,'含预订、在住与已退房'],['已取消待退款',cash(state.bookings.filter(b=>b.status==='已取消').reduce((n,b)=>n+paid(b),0)),'取消后不会自动退款，请核实后登记']])+`<div class="toolbar"><input class="search" id="orderSearch" aria-label="搜索订单" placeholder="搜索房号、客人、渠道或平台订单号" value="${esc(orderQuery)}"><select id="orderFilter" aria-label="订单状态">${['未完成','全部','预订','在住','已退房','已取消','停用'].map(s=>`<option ${s===orderFilter?'selected':''}>${s}</option>`).join('')}</select><a class="subtle-link" href="/api/payments.csv" download>导出收款流水 ↓</a></div><div class="panel"><div class="table-wrap"><table><thead><tr><th>房间 / 客人</th><th>入住 → 离店</th><th>渠道</th><th>状态</th><th>总房费</th><th>已收 / 待收</th><th>操作</th></tr></thead><tbody>${orders.map(b=>`<tr><td><strong>${b.room} · ${esc(b.guest)}</strong><small>#${b.id} ${esc(b.phone)}</small></td><td>${b.start} → ${b.end}<small>${nights(b.start,b.end)} 晚</small></td><td>${esc(b.channel)}<small>${esc(b.reference)}</small></td><td>${badge(b.status)}</td><td>${cash(b.total)}</td><td>${cash(paid(b))}<small>${b.status==='已取消'?'待退款 '+cash(paid(b)):'待收 '+cash(b.total-paid(b))}</small></td><td><div class="actions"><button class="small" data-action="edit" data-id="${b.id}">详情 / 续住</button>${b.status==='停用'?'':`<button class="small" data-action="payment" data-id="${b.id}">收 / 退款</button>`}</div></td></tr>`).join('')}</tbody></table>${orders.length?'':'<div class="empty"><strong>还没有符合条件的订单</strong>点击右上角新增，登记第一位客人。</div>'}</div></div><h2 class="report-title">最近收款流水</h2><div class="panel"><div class="table-wrap"><table><thead><tr><th>登记时间</th><th>订单 / 房间</th><th>方式</th><th>金额</th><th>备注</th></tr></thead><tbody>${state.payments.slice(-30).reverse().map(p=>`<tr><td>${esc(p.at.replace('T',' '))}</td><td>#${p.bookingId} · ${esc(state.bookings.find(b=>b.id===p.bookingId)?.room)}</td><td>${esc(p.method)}</td><td>${cash(p.amount)}</td><td>${esc(p.note)}</td></tr>`).join('')}</tbody></table>${state.payments.length?'':'<div class="empty">暂无收款流水</div>'}</div></div>`;
}
function renderSettings(){return `<div class="notice info"><div><strong>数据保存在本机文件，不依赖浏览器缓存</strong>每次保存前自动备份，保留最近 100 份。建议每天交班时再导出一份备份到 U 盘或另一台设备。</div></div><div class="panel"><div class="panel-head"><div><h2>房价与线下留房</h2><p>参考房价只用于新订单，可逐单修改；线下留房用于默认平台分配。</p></div><button class="primary small" data-action="settings">修改设置</button></div><div class="table-wrap"><table><thead><tr><th>房型</th><th>房号</th><th>参考房价 / 晚</th><th>默认线下留房</th></tr></thead><tbody>${Object.entries(state.rooms).map(([k,rs])=>`<tr><td><strong>${esc(k)}</strong><small>${rs.length} 间</small></td><td>${rs.join('、')}</td><td>${state.settings.rates[k]?cash(state.settings.rates[k]):'未设置'}</td><td>${state.settings.reserve[k]} 间</td></tr>`).join('')}</tbody></table></div></div><div class="panel"><div class="panel-head"><h2>备份与恢复</h2></div><div class="settings-body"><p class="settings-note">交班时点击“导出完整备份”，文件包含订单、收退款、分房及核对记录。恢复会替换当前数据，系统会先自动保留恢复前的一份备份。</p><div class="backup-actions"><a href="/api/backup" download>↓ 导出完整备份</a><button data-action="restore">从备份恢复</button><a href="/api/payments.csv" download>↓ 导出收款流水</a></div><p class="settings-note">平台结算款需实际到账后手工登记。本系统记录房费及收退款，不处理押金、发票或平台佣金。请在每天交班前核对携程、美团订单是否都已录入。</p></div></div><div class="panel"><div class="panel-head"><h2>最近操作</h2><span class="muted">共保留最近 2,000 条</span></div><div class="settings-body audit">${state.audit.slice(-50).reverse().map(a=>`<p><time>${esc(a.at.replace('T',' '))}</time>${esc(a.text)}</p>`).join('')||'<p class="muted">暂无操作记录</p>'}</div></div>`;}
function openModal(title,subtitle,body,foot){modalRevision=state.revision;modal.dataset.through='';$('#modalContent').innerHTML=`<div class="modal-head"><div><h2>${title}</h2><p>${subtitle}</p></div><button class="ghost" data-action="close" aria-label="关闭">✕</button></div><div class="modal-body">${body}</div><div class="modal-foot">${foot}</div>`;if(!modal.open)modal.showModal();}
const field=(label,html,full=false)=>`<label class="field ${full?'full':''}"><span>${label}</span>${html}</label>`;
const input=(name,value,type='text',extra='')=>`<input name="${name}" value="${esc(value)}" type="${type}" ${extra}>`;
const options=(list,value)=>list.map(x=>`<option value="${esc(x)}" ${x===value?'selected':''}>${esc(x)}</option>`).join('');
function bookingModal(id,room,d){
  const old=state.bookings.find(b=>b.id===Number(id));const start=d||selected;room=old?.room||room||allRooms().find(r=>!atRoom(r,start))||allRooms()[0];
  const b=old||{room,guest:'',phone:'',reference:'',notes:'',channel:'线下',status:start<=state.today?'在住':'预订',start,end:add(start,1),rate:state.settings.rates[typeOf(room)],total:state.settings.rates[typeOf(room)]};
  const body=`<form id="bookingForm" class="simple-booking"><div class="booking-room"><strong id="bookingRoomLabel">${room} · ${esc(typeOf(room))}</strong><span id="bookingStatusLabel">${esc(b.status)}</span><button type="button" id="changeBookingRoom" class="ghost small">换房</button></div><div class="form-grid">${field('入住日期',input('start',b.start,'date','required'))}${field('离店日期',input('end',b.end,'date','required'))}${field('客源',`<select name="channel">${options(['携程','美团','线下'],b.channel)}</select>`)}${field('总房费（元）',input('total',b.total?(b.total/100).toFixed(2):'','number','required min="0" max="1000000" step="0.01" placeholder="填写总金额"'))}</div><div class="booking-summary" id="bookingCalc"></div><details class="booking-more" id="bookingMore"><summary>更多信息（选填）</summary><div class="form-grid">${field('客人称呼',input('guest',b.guest,'text','maxlength="60" placeholder="可不填"'))}${field('电话',input('phone',b.phone,'tel','maxlength="30"'))}${field('房间',`<select name="room">${Object.entries(state.rooms).map(([k,rs])=>`<optgroup label="${esc(k)}">${rs.map(r=>`<option ${r===room?'selected':''} value="${r}">${r} · ${esc(k)}</option>`).join('')}</optgroup>`).join('')}</select>`)}${field('状态',`<select name="status">${options(old?['预订','在住','已退房','已取消','停用']:['预订','在住','停用'],b.status)}</select>`)}${field('平台订单号',input('reference',b.reference,'text','maxlength="100"'))}${field('备注',`<textarea name="notes" maxlength="1000" placeholder="可不填">${esc(b.notes)}</textarea>`,true)}</div></details></form>`;
  openModal(old?'修改 / 续住':'登记房间','',body,`${old&&old.status!=='停用'?`<button class="left" data-action="payment" data-id="${b.id}">收 / 退款</button>`:''}<button data-action="close">取消</button><button class="primary" type="submit" form="bookingForm">保存</button>`);
  const form=$('#bookingForm');
  let manualTotal=false,manualStatus=Boolean(old),rate=b.rate||Math.round(b.total/Math.max(1,nights(b.start,b.end)));
  function calculate(reprice=false){const f=form.elements;const n=nights(f.start.value,f.end.value);if(!manualStatus)f.status.value=f.start.value<=state.today?'在住':'预订';if(f.status.value==='停用')f.total.value='0.00';else if(reprice&&!manualTotal&&n>0&&rate>0)f.total.value=(rate*n/100).toFixed(2);const conflict=f.status.value!=='已取消'&&state.bookings.find(x=>x.id!==old?.id&&x.room===f.room.value&&x.status!=='已取消'&&x.start<f.end.value&&f.start.value<endOf(x));$('#bookingCalc').textContent=conflict?'这段时间已有订单，请换房或改日期。':`共 ${n>0?n:'—'} 晚${old?' · 已收 '+cash(paid(old)):''}`;$('#bookingRoomLabel').textContent=f.room.value+' · '+typeOf(f.room.value);$('#bookingStatusLabel').textContent=f.status.value;}
  $('#changeBookingRoom').addEventListener('click',()=>{$('#bookingMore').open=true;form.elements.room.focus();});
  form.addEventListener('input',e=>{if(e.target.name==='total')manualTotal=true;if(e.target.name==='status')manualStatus=true;calculate(['start','end'].includes(e.target.name));});
  form.addEventListener('change',e=>{if(e.target.name==='status'){manualStatus=true;if(e.target.value==='已退房'&&form.elements.start.value<=state.today&&form.elements.end.value>state.today){form.elements.end.value=form.elements.start.value===state.today?add(state.today,1):state.today;calculate(true);}}if(e.target.name==='room'&&!old){rate=state.settings.rates[typeOf(e.target.value)];calculate(true);}else calculate();});calculate();
  form.addEventListener('submit',async e=>{e.preventDefault();const raw=Object.fromEntries(new FormData(form));if(old)raw.id=old.id;raw.guest=raw.guest.trim()||(raw.status==='停用'?'房间停用':'未留姓名');const duration=nights(raw.start,raw.end);raw.rate=raw.status==='停用'?'0.00':old&&!manualTotal?(old.rate/100).toFixed(2):(Math.round(Number(raw.total)*100/Math.max(1,duration))/100).toFixed(2);const lastAllowed=raw.start===state.today?add(state.today,1):state.today;if(raw.status==='已退房'&&raw.end>lastAllowed){toast('请改为实际离店日期');return;}if(raw.status==='已取消'&&old?.status!=='已取消'&&!confirm('确认取消这笔订单？已有收款需要另行退款。'))return;if(Number(raw.total)===0&&raw.status!=='停用'&&!confirm('总房费为 0 元，确认保存？'))return;await save('booking',{booking:raw});});
}
function paymentModal(id){const b=state.bookings.find(b=>b.id===Number(id));if(!b)return;openModal('收款 / 退款',`${b.room} · ${esc(b.guest)} · 总房费 ${cash(b.total)} · 净收款 ${cash(paid(b))}`,`<form id="paymentForm"><div class="form-grid">${field('操作',`<select name="operation">${options(b.status==='已取消'?['退款']:['收款','退款'],b.status==='已取消'?'退款':'收款')}</select>`)}${field('金额（元）',input('amount','','number','required min="0.01" max="1000000" step="0.01"'))}${field('方式',`<select name="method">${options(['微信','支付宝','现金','银行卡','平台结算','其他'],'微信')}</select>`)}${field('备注',input('note','','text','maxlength="300"'))}</div><div class="calc">只登记已实际收取或退还的房费。平台待结算金额不要当作已收款；本页不会发起真实收款或退款。</div></form>`,`<button data-action="edit" data-id="${b.id}">返回订单</button><button type="submit" form="paymentForm" class="primary">登记流水</button>`);$('#paymentForm').addEventListener('submit',e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));save('payment',{bookingId:b.id,amount:f.amount,method:f.method,note:f.note,refund:f.operation==='退款'});});}
function allocationModal(d,k){const a=alloc(d,k);openModal('分配剩余房量',`${d} · ${esc(k)} · 当前剩余 ${a.free} 间`,`<form id="allocationForm"><div class="form-grid">${['ctrip','meituan','offline'].map((name,i)=>field(['携程可售','美团可售','线下留房'][i],input(name,a[name],'number',`required min="0" max="${a.free}" step="1"`))).join('')}</div><div class="calc">三项之和须等于 ${a.free}。此日期的手动分配会保留；后续房量不足时先保护线下留房，再自动缩减线上建议。增加库存后，新增空房默认留在线下，请重新分配。</div></form>`,`<button class="left" data-action="resetAllocation" data-date="${d}" data-kind="${esc(k)}">恢复默认均分</button><button data-action="close">取消</button><button class="primary" type="submit" form="allocationForm">保存分配</button>`);$('#allocationForm').addEventListener('submit',e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));save('allocate',{date:d,kind:k,ctrip:Number(f.ctrip),meituan:Number(f.meituan),offline:Number(f.offline)});});}
function confirmModal(d,k){const a=alloc(d,k);openModal('确认平台已经调整',`${d} · ${esc(k)}`,`<form id="confirmForm"><div class="notice"><div><strong>请先去携程和美团后台实际操作</strong>先减少 / 关房，再增加库存。检查同房型的全部售卖产品，避免重复放量。</div></div>${stats([['携程剩余可售',a.ctrip+'<small> 间</small>',a.ctrip===0?'请确认已关房':'请确认后台数字一致'],['美团剩余可售',a.meituan+'<small> 间</small>',a.meituan===0?'请确认已关房':'请确认后台数字一致']])}<label class="inline-check"><input type="checkbox" required><span>我已核对 <strong>${d}</strong> 当晚的<strong>${esc(k)}</strong>，携程剩余可售为 <strong>${a.ctrip}</strong>，美团为 <strong>${a.meituan}</strong>。这是人工操作记录，不代表系统自动同步。</span></label></form>`,`<button data-action="close">尚未调整</button><button type="submit" form="confirmForm" class="primary">记录本次核对</button>`);$('#confirmForm').addEventListener('submit',e=>{e.preventDefault();save('confirm',{date:d,kind:k,ctrip:a.ctrip,meituan:a.meituan});});}
function settingsModal(){openModal('房价与留房设置','设置默认值，不会更改已登记订单的成交金额。',`<form id="settingsForm">${Object.keys(state.rooms).map((k,i)=>`<div class="setting-row"><strong>${esc(k)}</strong>${field('参考房价 / 晚',input('rate'+i,(state.settings.rates[k]/100).toFixed(2),'number','required min="0" max="1000000" step="0.01"'))}${field('默认线下留房',input('reserve'+i,state.settings.reserve[k],'number',`required min="0" max="${state.rooms[k].length}" step="1"`))}</div>`).join('')}<div class="calc">未手动分配的日期会按新设置重算。单日已经手动分配的房量保持原规则；如需应用默认值，在平台调房中点击“恢复默认均分”。</div></form>`,`<button data-action="close">取消</button><button type="submit" form="settingsForm" class="primary">保存设置</button>`);$('#settingsForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target),settings={rates:{},reserve:{}};Object.keys(state.rooms).forEach((k,i)=>{settings.rates[k]=f.get('rate'+i);settings.reserve[k]=Number(f.get('reserve'+i));});save('settings',{settings});});}
function restoreModal(){openModal('从完整备份恢复','恢复会替换目前的订单、收退款与调房记录。',`<form id="restoreForm"><div class="form-grid">${field('选择本系统导出的 JSON 备份','<input type="file" name="backup" accept=".json,application/json" required>',true)}${field('请输入“恢复备份”以确认替换',input('phrase','','text','required pattern="恢复备份" autocomplete="off"'),true)}</div><div class="calc">恢复前会自动备份当前数据。请确认这是本店正确日期的备份，并先导出当前数据留存。</div></form>`,`<button data-action="close">取消</button><button class="danger-button" type="submit" form="restoreForm">恢复备份</button>`);$('#restoreForm').addEventListener('submit',async e=>{e.preventDefault();const file=e.target.elements.backup.files[0];if(!file)return;if(file.size>20000000){toast('备份文件不能超过 20 MB');return;}try{const backup=JSON.parse(await file.text());await save('restore',{backup});}catch{toast('文件不是有效的 JSON 备份');}});}
function setAllocationRange(from,through,kind){
  modal.dataset.through=through||from;
  const label=through&&through!==from?`${from} 至 ${through}（含首尾，共 ${nights(from,through)+1} 晚）`:from;
  const a=alloc(from,kind);
  $('.modal-head p').textContent=`${label} · ${kind} · 每晚剩余 ${a.free} 间`;
  const check=$('#confirmForm .inline-check span');
  if(check)check.textContent=`我已核对 ${label} 的${kind}，以上每晚携程剩余可售均为 ${a.ctrip} 间，美团均为 ${a.meituan} 间。这是人工操作记录，不代表系统自动同步。`;
  if($('#allocationForm')&&through!==from)$('#allocationForm .calc').textContent+=' 本次分配适用于上方整段日期的每一晚。';
}
document.addEventListener('click',e=>{
  const b=e.target.closest('button');if(!b||busy)return;
  if(b.dataset.view){view=b.dataset.view;render();return;}
  if(b.dataset.mode){roomMode=b.dataset.mode;render();return;}
  const a=b.dataset.action;
  if(a==='new')bookingModal(null,b.dataset.room,b.dataset.date);
  if(a==='edit')bookingModal(b.dataset.id);
  if(a==='payment')paymentModal(b.dataset.id);
  if(a==='close')modal.close();
  if(a==='dayPrev'){selected=add(selected,-1);render();}
  if(a==='dayNext'){selected=add(selected,1);render();}
  if(a==='today'){selected=state.today;render();}
  if(a==='togglePending'){pendingOnly=!pendingOnly;render();}
  if(a==='allocate'){allocationModal(b.dataset.date,b.dataset.kind);setAllocationRange(b.dataset.date,b.dataset.through,b.dataset.kind);}
  if(a==='confirm'){confirmModal(b.dataset.date,b.dataset.kind);setAllocationRange(b.dataset.date,b.dataset.through,b.dataset.kind);}
  if(a==='resetAllocation')save('allocate',{date:b.dataset.date,kind:b.dataset.kind,reset:true});
  if(a==='settings')settingsModal();
  if(a==='restore')restoreModal();
});
document.addEventListener('change',e=>{if(e.target.id==='roomDate'&&e.target.value){selected=e.target.value;render();}if(e.target.id==='syncDate'&&e.target.value){syncDate=e.target.value<state.today?state.today:e.target.value;render();}if(e.target.id==='syncDays'){syncDays=Number(e.target.value);render();}if(e.target.id==='orderFilter'){orderFilter=e.target.value;render();}});
let searchTimer;document.addEventListener('input',e=>{if(e.target.id==='orderSearch'){orderQuery=e.target.value;clearTimeout(searchTimer);searchTimer=setTimeout(()=>{const pos=e.target.selectionStart;render();$('#orderSearch')?.focus();$('#orderSearch')?.setSelectionRange(pos,pos);},180);}});
modal.addEventListener('cancel',e=>{if(busy)e.preventDefault();});
refresh(true);setInterval(()=>{if(!busy&&!modal.open)refresh();},15000);
