const {chromium}=require(process.argv[2]||'playwright');
const assert=require('node:assert/strict');
const sample=process.argv[3];
(async()=>{
  const browser=await chromium.launch({executablePath:'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe',headless:true});
  try{
    const page=await browser.newPage({viewport:{width:1280,height:1000}}),errors=[];
    page.on('pageerror',error=>errors.push(error.message));
    await page.goto('http://127.0.0.1:8766/');
    await page.locator('.room').first().waitFor();
    assert.match(await page.locator('#otaFreshness').innerText(),/尚未导入/);
    await page.locator('#otaImportButton').click();
    await page.locator('#otaFile').setInputFiles(sample);
    await page.locator('#otaCommit').waitFor();
    assert.match(await page.locator('#otaImportPreview').innerText(),/22 笔订单/);
    assert.equal(await page.locator('[data-product]').count(),4);
    await page.locator('#otaMappingConfirmed').check();
    await page.locator('#otaCommit').click();
    await page.locator('#otaOrderList').waitFor();
    const state=await (await page.request.get('http://127.0.0.1:8766/api/state')).json();
    assert.equal(state.otaOrders.length,22);
    assert.equal(state.inventory['2026-09-30']['标准间'].free,0);
    assert.equal(state.inventory['2026-10-01']['大床房'].free,0);
    assert.match(await page.locator('#closurePreview').innerText(),/标准间/);
    await page.locator('[data-close]').click();
    await page.locator('#allAlertsButton').click();
    const alert=page.locator('.closure-alert-row').filter({hasText:'09-30 · 标准间'});
    assert.equal(await alert.count(),1);
    await alert.locator('[data-platform=ctrip]').click();
    await page.locator('.closure-alert-row').filter({hasText:'09-30 · 标准间'}).locator('[data-platform=ctrip].done').waitFor();
    assert.match(await page.locator('.closure-alert-row').filter({hasText:'09-30 · 标准间'}).innerText(),/携程\/去哪儿已核对/);
    await page.locator('[data-close]').click();
    await page.locator('#datePicker [data-date="2026-09-30"]').click();
    assert.match(await page.locator('.room-group').first().innerText(),/剩 0 \/ 4 间/);
    await page.locator('[data-room="8302"]').click();
    assert.ok(await page.locator('[name=otaOrderId]').count());
    await page.locator('[name=otaOrderId]').selectOption({index:1});
    await page.locator('#paidAmount').fill('200');
    await page.locator('#checkinForm button[type=submit]').click();
    await page.locator('dialog').waitFor({state:'hidden'});
    const after=await (await page.request.get('http://127.0.0.1:8766/api/state')).json();
    assert.equal(after.inventory['2026-09-30']['标准间'].free,0);
    assert.equal(after.bookings[0].otaOrderId.length>0,true);
    await page.locator('#otaOrdersButton').click();
    await page.locator('#addMeituanOrder').click();
    await page.locator('#otaManualForm [name=orderId]').fill('MT-UI-100');
    await page.locator('#otaManualForm [name=kind]').selectOption('高级观景');
    await page.locator('#otaManualForm [name=start]').fill('2026-10-12');
    await page.locator('#otaManualForm [name=end]').fill('2026-10-13');
    await page.locator('#otaManualForm [name=quantity]').fill('1');
    await page.locator('#otaManualForm button[type=submit]').click();
    await page.locator('#otaOrderList').waitFor();
    const withMeituan=await (await page.request.get('http://127.0.0.1:8766/api/state')).json();
    assert.equal(withMeituan.otaOrders.length,23);
    assert.ok(withMeituan.closureAlerts.some(a=>a.date==='2026-10-12'&&a.kind==='高级观景'));
    await page.locator('[data-close]').click();
    await page.setViewportSize({width:390,height:844});
    assert.equal(await page.locator('body').evaluate(e=>e.scrollWidth<=window.innerWidth),true);
    assert.deepEqual(errors,[]);
    console.log('PASS: .xls preview, mapped import, full-date reminders, per-platform check, linked room without double count, manual future Meituan order, mobile.');
  }finally{await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
