const {chromium}=require(process.argv[2]||'playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path');
(async()=>{
  const browser=await chromium.launch({executablePath:'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe',headless:true});
  try{
    const page=await browser.newPage({viewport:{width:1280,height:1080}}),errors=[];
    page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
    const base='http://127.0.0.1:8766';
    const read=async()=>await(await page.request.get(base+'/api/state')).json();
    const post=async(action,data)=>{const s=await read();const r=await page.request.post(base+'/api/'+action,{headers:{'X-Kasho-Request':'frontdesk'},data:{...data,revision:s.revision}});assert.equal(r.status(),200,await r.text());return await r.json();};
    let s=await read();
    const add=(d,n)=>{const x=new Date(d+'T12:00:00');x.setDate(x.getDate()+n);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`;};
    const start=add(s.today,1),end=add(s.today,4);
    const orders=[{id:'test-standard',kind:'标准间',quantity:4},{id:'test-comfort',kind:'舒适观景',quantity:4}].map(o=>({...o,product:o.kind,site:'携程',status:'已接单',start,end,guest:'测试王先生'}));
    await post('restore',{backup:{...s,otaOrders:orders}});
    await page.goto(base);await page.locator('.room').first().waitFor();
    await page.locator(`[data-date="${start}"]`).click();
    assert.equal(await page.locator('#freeCount').innerText(),'5');
    await page.locator('[data-pending-kind="标准间"]').click();
    await page.locator('[data-order="test-standard"]').click();
    await page.locator('#otaKeepQuantity').fill('1');
    await page.locator('#otaQuantityForm button[type=submit]').click();
    await page.waitForFunction(()=>document.querySelector('#otaKeepQuantity')?.value==='1'&&document.querySelectorAll('[data-ota-cancel]').length===1);
    assert.match(await page.locator('#modalContent').innerText(),/本机保留 1/);
    await page.locator('[data-close]').click();
    assert.equal(await page.locator('#freeCount').innerText(),'8');
    await post('ota-assign',{orderId:'test-comfort'});
    await page.reload();await page.locator(`[data-date="${start}"]`).click();
    assert.equal(await page.locator('#freeCount').innerText(),'8');
    assert.equal(await page.locator('#onlineTotal').innerText(),'¥1,262.80');
    assert.equal(await page.locator('.room-note').count(),5);
    await page.locator(`[data-date="${add(start,1)}"]`).click();
    assert.equal(await page.locator('#freeCount').innerText(),'8');
    assert.equal(await page.locator('#onlineTotal').innerText(),'¥1,262.80');
    await page.locator(`[data-date="${end}"]`).click();
    assert.equal(await page.locator('#freeCount').innerText(),'13');
    await page.locator(`[data-date="${start}"]`).click();
    await page.locator('[data-room="8302"]').click();
    assert.match(await page.locator('.stay-date').first().innerText(),/3 晚/);
    await page.locator('#cancelBooking').click();
    await page.waitForFunction(()=>!document.querySelector('#modal').open);
    assert.equal(await page.locator('#freeCount').innerText(),'9');
    s=await read();assert.equal(s.inventory[start]['标准间'].unassigned,0);
    await page.locator('[data-room="8306"]').click();
    assert.equal(await page.locator('#paidAmount').inputValue(),'178.64');
    await page.locator('[name=nights]').selectOption('3');
    assert.equal(await page.locator('#paidAmount').inputValue(),'535.92');
    await page.locator('#paidAmount').fill('500');
    await page.locator('[name=nights]').selectOption('4');
    assert.equal(await page.locator('#paidAmount').inputValue(),'500');
    await page.locator('[data-close]').first().click();
    await page.locator('#otaOrdersButton').click();await page.locator('[data-order="test-standard"]').click();
    await page.locator('#otaKeepQuantity').fill('1');await page.locator('#otaQuantityForm button[type=submit]').click();
    await page.waitForFunction(()=>document.querySelectorAll('[data-ota-cancel]').length===1);
    const out=path.join(__dirname,'../test-artifacts');fs.mkdirSync(out,{recursive:true});
    await page.screenshot({path:path.join(out,'ota-lifecycle-dialog.png')});
    await page.setViewportSize({width:390,height:844});
    assert.equal(await page.locator('body').evaluate(e=>e.scrollWidth<=innerWidth),true);
    assert.equal(await page.locator('#modal').evaluate(e=>e.scrollWidth<=e.clientWidth),true);
    await page.locator('[data-close]').click();await page.setViewportSize({width:1280,height:1080});
    await page.screenshot({path:path.join(out,'ota-lifecycle-dashboard.png'),fullPage:true});
    assert.deepEqual(errors,[]);
    console.log('PASS: pending quantity editing, partial cancellation, full-stay occupancy and exact totals, departure release, visible names, room cancellation, default/manual prices, restore and mobile.');
  }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
