'use strict';
function openMonthly(month=state.today.slice(0,7)){
  const report=KashoMoney.monthReport(state,month);modal.classList.add('records-modal');dialogRevision=state.revision;
  const summaryRow=(name,group)=>`<tr><th>${name}</th><td>${yuan(group.online)}</td><td>${yuan(group.offline)}</td><td>${yuan(group.total)}</td></tr>`;
  $('#modalContent').innerHTML=`<div class="modal-head"><h2 id="dialogTitle">每月汇总</h2><button class="close" data-close aria-label="关闭">×</button></div><div class="modal-body"><label class="reconcile-date">统计月份 <input id="reportMonth" aria-label="统计月份" type="month" value="${esc(month)}" min="0001-01" max="9998-12" required></label><p class="batch-note">按住宿日归入月份，跨月只计本月部分。已入住 / 已退房与预订分开；不是实际到账或平台结算款。</p><div class="month-cards"><div><span>线上住宿金额</span><strong id="monthOnline">${yuan(report.stays.online)}</strong></div><div><span>线下住宿金额</span><strong id="monthOffline">${yuan(report.stays.offline)}</strong></div><div><span>住宿金额合计</span><strong id="monthTotal">${yuan(report.stays.total)}</strong></div><div><span>售出间夜（按登记）</span><strong id="monthNights">${report.soldNights}</strong></div></div><p class="batch-note">上面只统计状态为“在住 / 已退房”的记录。1 间房登记住 1 晚算 1 间夜，同房同日不重复计数；金额仍逐笔累计。包含登记的后续晚数，不代表已经全部住完。</p><div class="money-table-wrap"><table class="money-table"><thead><tr><th>统计范围</th><th>线上</th><th>线下</th><th>合计</th></tr></thead><tbody>${summaryRow('已入住 / 已退房',report.stays)}${summaryRow('预订（单列）',report.reserved)}${summaryRow('全部登记金额',report.all)}</tbody></table></div><p class="batch-note">另有预订 ${report.reservedNights} 间夜。全部登记金额已包含上面两类，不要重复相加。取消、删除、停用不计入；未确认到店的记录仍归预订。</p><details id="monthDaily"><summary>按天核对</summary><div class="money-table-wrap"><table class="money-table"><thead><tr><th>日期</th><th>住宿金额</th><th>预订金额</th><th>售出间夜</th><th></th></tr></thead><tbody>${report.dates.map(d=>`<tr><td>${d.date.slice(5)}</td><td>${yuan(d.stays.total)}</td><td>${yuan(d.reserved.total)}</td><td>${d.soldNights}</td><td><button data-month-day="${d.date}">日明细</button></td></tr>`).join('')}</tbody></table></div></details><h3 class="month-subtitle">逐笔明细 · ${report.rows.length} 条</h3><p class="batch-note">“本月晚数”按每条记录列出；同房同日多笔记录可相加金额，但售出间夜已去重。</p><div class="money-table-wrap"><table class="money-table"><thead><tr><th>房号 / 日期</th><th>客源 / 状态</th><th>本月晚数</th><th>本月金额</th><th></th></tr></thead><tbody id="monthRows"></tbody></table></div><div class="record-pages"><button id="monthPrevious">上一页</button><span id="monthPage"></span><button id="monthNext">下一页</button></div><p class="batch-note month-endnote">此报表按当前登记状态计算，编辑、取消或删除旧记录后会相应变化。缺少的历史记录不会自动补齐。</p></div>`;
  let page=0;const rows=report.rows.slice().sort((a,b)=>b.booking.start.localeCompare(a.booking.start)||b.booking.id-a.booking.id);
  $('.modal-body>.batch-note').textContent='按住宿日归入月份，跨月只计本月部分。统计房费（含未付），不是实际到账；已入住 / 已退房与预订分开。';
  $('.money-table tbody').insertAdjacentHTML('beforeend',summaryRow('全部金额中：已付',report.settled)+summaryRow('全部金额中：未付',report.unpaid));
  function list(){
    $('#monthRows').innerHTML=rows.slice(page*20,page*20+20).map(({booking:b,nights,cents})=>`<tr data-month-id="${b.id}"><td>${esc(b.room)} · #${b.id}<small>${esc(b.start)} → ${esc(b.end)}</small></td><td>${esc(b.channel)}<small>${esc(b.status)}</small></td><td>${nights}</td><td>${yuan(cents)}</td><td><button data-month-edit="${b.id}">查看 / 编辑</button></td></tr>`).join('')||'<tr><td colspan="5">本月暂无有效记录</td></tr>';
    $('#monthPage').textContent=`第 ${page+1} / ${Math.max(1,Math.ceil(rows.length/20))} 页`;
    $('#monthRows').querySelectorAll('[data-month-id]').forEach(tr=>{const b=state.bookings.find(x=>x.id===Number(tr.dataset.monthId)),small=document.createElement('small');small.textContent=paymentLabel(b);tr.cells[1].append(small);});
    $('#monthPrevious').disabled=page===0;$('#monthNext').disabled=(page+1)*20>=rows.length;
  }
  $('#monthPrevious').addEventListener('click',()=>{page--;list();});$('#monthNext').addEventListener('click',()=>{page++;list();});
  $('#reportMonth').addEventListener('change',e=>{if(e.target.validity.valid&&e.target.value)openMonthly(e.target.value);});
  $('#monthRows').addEventListener('click',e=>{const b=e.target.closest('[data-month-edit]');if(b&&!busy)openEdit(Number(b.dataset.monthEdit));});
  $('#monthDaily').addEventListener('click',e=>{const b=e.target.closest('[data-month-day]');if(b&&!busy)openMoney(b.dataset.monthDay);});
  list();if(!modal.open)modal.showModal();
}
$('#monthlyButton').addEventListener('click',()=>{if(state&&!busy)openMonthly();});
